################################################################################
#   Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
################################################################################
---
######################## Enfine Properties #####################################
# Unique Id of the Humantask Engine.

engineId: default-engine
# Name of the Humantask Engine.
name: WSO2 WS-HumanTask 1.1 engine

######################## People query releated configration. ###################
peopleQueryConfiguration:

  # People Query Evaluator implementation.
  peopleQueryEvaluator: org.wso2.carbon.humantask.engine.runtime.impl.people.CaasBasedPeopleQueryEvaluator

  # Define bellow additional user defined properties related people query evaluator implementaiton.
  # Note !!! Following propereis are only applicable for
  # "org.wso2.carbon.humantask.engine.runtime.impl.people.CaasBasedPeopleQueryEvaluator" implementation. Other
  # implementation may have defferent properties.
  properties:
#    Check User exists in configured carbon user store.
    CheckUserExistence: true
#    # Check Group exists in configured carbon user store.
    CheckGroupExistence: "true"
#    # Enable caching support for People queries. Results of people quries will be cached for defined time period.
    EnableCache : false
#    # Cache expiry time in seconds. Only effect when EnableCache = true.
    CacheExpiryTime : 900

######################## Data source releated configuration. ###################
dataSource:

  # Run in Memory mode.
  # WARNING !!!  "runInMemory = true" is not production recommended. Data will loss once server restarted.
  # Only for demostation perpose only. To run in persisted mode, set runInMemory = false.
  runInMemory: false

  # Datasource Name of the HumanTask Datasource. Only effects when runs only in persisted mode. ( runInMemory = false )
  humanTaskDataSource: HumanTask
  # Audit and Event DataSource
  auditDataSource: HumanTaskAudit
  # History DataSource
  historyDataSource: HumanTaskHistory